[package]
name = "koai"
version = "1.0.8"
authors = ["psyche"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rs_utils"
path = "koai/utils/text.rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "*"
features = ["extension-module"]